### ISSUE TITLE
Dependencies Installation issue

### ISSUE THREAD

**Issue by heye0507** [turingaicloud/quickstart#2]
**Issue:**

When calling tcloud init, some of the dependencies in the tuxiv.conf cannot be installed. Adding package to channel doesn't work ethier.

**Reproduce:**
1. Things in the conda-forge package
Eg: opencv-python
2. Some 3rd party dependent framework, such as fastai

**Expected behavior:**
Packages can be installed via tuxiv.conf

**Current work around:**

adding pip command in the entrypoints to install the package when submitting job
or pulling github repo to install the package directly in the job files.

**Comment by xcwanAndy** [comment]
@heye0507 Hi, He.

"When calling tcloud init". Do you mean when calling `tcloud submit`?

**Comment by heye0507** [comment]
Yes, I meant `tcloud submit`.

**Comment by xcwanAndy** [comment]
Closing this issue. Please feel free to reopen if things did not work.
